name: PlayerTpa
version: '${project.version}'
main: playertpa.playertpa.PlayerTpa
api-version: 1.18
authors: [ tw_abc ]
commands:
  tpa:
  tpahere:
  tpno:
  tpyes:
  tpacancel:
  tpdeny:
  tpaccept:

